language: c

compiler:
        - gcc

before_install:
        - uname -a
        - lsb_release -a
        - sudo apt-add-repository --yes ppa:zoogie/sdl2-snapshots
        - sudo apt-get update -qq

install:
        - sudo apt-get install -qq libsdl2-dev libsdl2-ttf-dev libsdl2-mixer-dev libsdl2-image-dev
        - git clone -b release_0.1 git://github.com/nardinan/miranda
        - echo $(cd miranda && mkdir build && cd build && cmake .. && make && sudo make install)

script:
        - mkdir build
        - cd build
        - cmake ..
        - make
